# Generated by Django 5.0.3 on 2024-04-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=33, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=33)),
                ('lastName', models.CharField(blank=True, max_length=33)),
                ('email', models.EmailField(blank=True, max_length=33)),
                ('password', models.CharField(max_length=33)),
                ('address', models.CharField(blank=True, max_length=99)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('profilePicture', models.URLField(blank=True, max_length=255)),
                ('userGroup', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=5)),
                ('userRating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registerDate', models.DateField(blank=True, null=True)),
                ('lastLoginDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
