# Generated by Django 5.0.3 on 2024-04-10 06:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(db_column='itemId', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=33)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryid', models.IntegerField(blank=True, db_column='categoryId', null=True)),
                ('size', models.CharField(blank=True, max_length=33, null=True)),
                ('brand', models.CharField(blank=True, max_length=33, null=True)),
                ('itemcondition', models.CharField(blank=True, db_column='itemCondition', max_length=15, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('List_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=33, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=33, null=True)),
                ('lastname', models.CharField(blank=True, max_length=33, null=True)),
                ('email', models.EmailField(max_length=33, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=99, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profilePicture', models.CharField(blank=True, max_length=255, null=True)),
                ('userGroup', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10)),
                ('userRating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('lastLoginDate', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='mypage_user_set', related_query_name='mypage_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='mypage_user_set', related_query_name='mypage_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bidtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='mypage.item')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('startprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buynowprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endtime', models.DateField(default=datetime.datetime(2024, 4, 15, 6, 10, 19, 401703, tzinfo=datetime.timezone.utc))),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_seller', to=settings.AUTH_USER_MODEL)),
                ('currentbid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='mypage.bid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='mypage.item')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=255)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mypage.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='mypage.item')),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
