# Generated by Django 5.0.3 on 2024-04-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=33, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=33, null=True)),
                ('lastname', models.CharField(blank=True, max_length=33, null=True)),
                ('email', models.EmailField(max_length=33, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=99, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profilePicture', models.CharField(blank=True, max_length=255, null=True)),
                ('userGroup', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10)),
                ('userRating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('lastLoginDate', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='mypage_user_set', related_query_name='mypage_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='mypage_user_set', related_query_name='mypage_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
