# Generated by Django 5.0.3 on 2024-04-05 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.IntegerField(db_column='itemId', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=33)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryid', models.IntegerField(blank=True, db_column='categoryId', null=True)),
                ('size', models.CharField(blank=True, max_length=33, null=True)),
                ('brand', models.CharField(blank=True, max_length=33, null=True)),
                ('itemcondition', models.CharField(blank=True, db_column='itemCondition', max_length=15, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='mypage.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
