# Generated by Django 5.0.3 on 2024-04-10 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='currentbid',
        ),
        migrations.AlterField(
            model_name='auction',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 6, 40, 2, 896594, tzinfo=datetime.timezone.utc)),
        ),
    ]
