# Generated by Django 5.0.3 on 2024-04-10 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_remove_auction_buyer_remove_auction_currentbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 0, 8, 564327, tzinfo=datetime.timezone.utc)),
        ),
    ]
