# Generated by Django 5.0.3 on 2024-04-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionid', models.AutoField(db_column='auctionId', primary_key=True, serialize=False)),
                ('itemid', models.IntegerField(db_column='itemId')),
                ('sellerid', models.IntegerField(db_column='sellerId')),
                ('buyerid', models.IntegerField(blank=True, db_column='buyerId', null=True)),
                ('status', models.CharField(max_length=15)),
                ('startprice', models.DecimalField(blank=True, db_column='startPrice', decimal_places=2, max_digits=10, null=True)),
                ('currentbid', models.DecimalField(blank=True, db_column='currentBid', decimal_places=2, max_digits=10, null=True)),
                ('buynowprice', models.DecimalField(blank=True, db_column='buyNowPrice', decimal_places=2, max_digits=10, null=True)),
                ('postdate', models.DateField(blank=True, db_column='postDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='endDate', null=True)),
            ],
            options={
                'db_table': 'Auction',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
