# Generated by Django 5.0.3 on 2024-04-10 13:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_alter_auction_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currentTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 45, 41, 668693, tzinfo=datetime.timezone.utc)),
        ),
    ]
