# Generated by Django 5.0.3 on 2024-04-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auction_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.AutoField(db_column='itemId', primary_key=True, serialize=False),
        ),
    ]
