# Generated by Django 5.0.3 on 2024-04-10 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_item_currenttime_alter_auction_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 14, 30, 42, 407695, tzinfo=datetime.timezone.utc)),
        ),
    ]
