# Generated by Django 5.0.3 on 2024-04-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_alter_item_itemid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
