# Generated by Django 5.0.3 on 2024-04-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_alter_auction_table_alter_item_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auction',
            table='Auction',
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
