# Generated by Django 5.0.3 on 2024-04-07 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_alter_auction_table_alter_item_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='List_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
