# Generated by Django 5.0.3 on 2024-04-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
