# Generated by Django 5.0.3 on 2024-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0010_alter_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidtime',
            field=models.DateField(blank=True, db_column='bidTime', null=True),
        ),
    ]
