# Generated by Django 5.0.3 on 2024-04-09 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0011_bid_bidtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
